<div id="poll_create">
	<?php if($this->event) { ?>
	<h2>Ajouter un sondage pour l'évènement <em><?php echo $this->event->title (); ?></em></h2>
	<a href="<?php echo Url::display (array ('c' => 'event', 'a' => 'see', 'params' => array ('id' => $this->event->id ()))); ?>">← Retour à l'évènement</a>
	<?php } else { ?>
	<h2>Créer un sondage</h2>
	<a href="<?php echo Url::display (); ?>">← Retour à l'accueil</a>
	<?php } ?>

	<form class="form-horizontal" method="post" action="<?php echo $this->event ? Url::display (array ('c' => 'poll', 'a' => 'create', 'params' => array ('id' => $this->event->id ()))) : Url::display (array ('c' => 'poll', 'a' => 'createalone')); ?>">
		<?php if (!empty ($this->missing)) { ?>
		<div class="alert alert-error">Vous n'avez pas rempli tous les champs correctement!</div>
		<?php } ?>
		<?php if (isset ($this->error)) { ?>
		<div class="alert alert-error">Une erreur est survenue :(</div>
		<?php } ?>

		<div class="control-group <?php if (in_array ('title', $this->missing)) { echo ' error'; } ?>">
			<label class="control-label" for="titlePoll">Titre du sondage</label>
			<div class="controls">
				<input class="input-xlarge" type="text" name="title" id="titlePoll" <?php if (!empty ($this->values['title'])) { echo 'value="' . $this->values['title'] . '"'; } ?>/>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="expirationdateEvent">Date d'expiration des inscriptions</label>
			<div class="controls">
				<input class="input-xlarge" type="date" name="expirationdate" id="expirationdateEvent" value="<?php if (!empty ($this->values['expirationdateEvent'])) { echo $this->values['expirationdateEvent']; } else { echo date ('Y-m-d', time () + 86400); } ?>" />
			</div>
		</div>
		<div class="control-group <?php if (in_array ('choices', $this->missing)) { echo ' error'; } ?>">
			<label class="control-label" for="choicesPoll">Choix du sondage (un par ligne)</label>
			<div class="controls">
				<textarea class="input-xlarge" name="choices" id="choicesPoll"><?php if (!empty ($this->values['choices'])) { echo $this->values['choices']; } ?></textarea>
			</div>
		</div>
		<div class="control-group">
			<div class="controls">
				<button type="submit" class="btn btn-default btn-lg input-xlarge">Créer</button>
			</div>
		</div>
	</form>
</div>
