<div id="poll_see">
	<div class="post">
		<h1>Sondage <em><?php echo $this->poll->title (); ?></em>
		<?php if(isset($this->event)) {?>
		(<?php echo $this->event->title (); ?>)
		</h1>
		<a href="<?php echo Url::display (array ('c' => 'event', 'a' => 'see', 'params' => array ('id' => $this->event->id ()))); ?>">← Retour à l'évènement</a>
		<?php } else {?>
		</h1>
		<?php } ?>

		
		<?php 
		$nb_votes = array ();
		if($this->poll->expirationdate() > time ()) {
		?>
		<!-- formulaire pour ajouter un utilisateur, utilise html5 -->
		<form id="add_voter" method="post" action="<?php echo Url::display (array ('c' => 'poll', 'a' => 'vote', 'params' => array ('id' => $this->poll->id ()))); ?>">
		</form>
		<p>Les inscriptions se fermeront le <?php echo timestamptodate ($this->poll->expirationdate(), true); ?>.</p>
		<?php
		} else {
		?>
		<p>Les inscriptions sont fermées.</p>
		<?php
		}
		?>
		<table class="table table-striped">
			<thead>
				<tr>
					<th class="none">&nbsp;</th>
					<th class="none">&nbsp;</th>
					<?php foreach ($this->poll->choices () as $key => $c) { ?>
					<?php $nb_votes[$key] = 0; ?>
					<th id="choice_<?php echo $key; ?>" class="choice"><?php echo $c; ?></th>
					<?php } ?>
					<th class="none">&nbsp;</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->poll->voters () as $key => $choices) { ?>
				<tr>
					<td class="name_voter"><i class="icon-user"></i> <?php echo $key; ?> </td>
					<td class="manage_vote"></td>
					<?php foreach ($this->poll->choices () as $key => $c) { ?>
					<?php
						$vote = in_array ($key, $choices);
						if ($vote) {
							$nb_votes[$key]++;
						}
					?>
					<td class="<?php echo $vote ?  'vote' : 'non_vote'; ?>"><?php echo $vote ? '<i class="icon-ok"></i>' : '<i class="icon-remove-sign"></i>'; ?></td>
					<?php } ?>
					<td class="none">&nbsp;</td>
				</tr>
				<?php 
				}
				if($this->poll->expirationdate() > time ()) {
				?>
				
				<tr>
					<td class="name_voter"><input id="name_add_voter" form="add_voter" type="text" name="voter" placeholder="Votre nom" /></td>
					<td class="none">&nbsp;</td>
					<?php foreach ($this->poll->choices () as $key => $c) { ?>
					<td><span class="for_checkbox"><input form="add_voter" type="checkbox" name="choices[]" value="<?php echo $key; ?>" /></span></td>
					<?php } ?>
					<td><button id="submit_add_voter" form="add_voter" class="btn btn-primary" type="submit"><i class="icon-white icon-plus"></i></button></td>
				</tr>
				<?php 
				}
				if (count ($this->poll->voters ()) >= 5) { 
				?>
	
				<tr>
					<td class="none">&nbsp;</td>
					<td class="none">&nbsp;</td>
					<?php foreach ($this->poll->choices () as $key => $c) { ?>
					<td id="choice_<?php echo $key; ?>" class="choice"><?php echo $c; ?></td>
					<?php } ?>
					<td class="none">&nbsp;</td>
				</tr>
				<?php } ?>
				
				<tr class="info">
					<td class="total">&nbsp;</td>
					<td class="none">&nbsp;</td>
					<?php
						ksort ($nb_votes);
						$max = max ($nb_votes);
					?>
					<?php foreach ($nb_votes as $key => $nb) { ?>
					<td class="nb_votes<?php echo ($nb >= $max) ? ' max' : ''; ?>"><?php echo $nb; ?></td>
					<?php } ?>
					<td class="none">&nbsp;</td>
				<tr>
					
			</tbody>
		</table>
	</div>
</div>
