<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<?php echo self::headTitle(); ?>
		<?php echo self::headStyle(); ?>
	</head>
	<body>
<nav class="navbar navbar-default" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="brand" href="<?php echo Url::display (); ?>"><?php echo Configuration::title (); ?></a>
		</div>
		<div>
			<ul class="nav navbar-nav">
				<li <?php echo Request::controllerName() == 'index' && Request::actionName() == 'index' ? 'class="active"' : ''; ?>>
					<a href="<?php echo Url::display (); ?>">Accueil</a>
				</li>
				<?php if (!is_logged ()) { ?>
				<li><a id="signin" href="#">Connectez vous</a></li>
				<?php } else { ?>
				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">
						<?php echo Session::param ('mail'); ?>
						<b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li><a href="#">Profil</a></li>
						<li><a id="signout" href="#">Déconnexion</a></li>
					</ul>
				</li>
				<?php } ?>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li <?php echo Request::controllerName() == 'index' && Request::actionName() == 'about' ? 'class="active"' : ''; ?>>
					<a href="<?php echo Url::display (array ('c' => 'index', 'a' => 'about')); ?>">À propos</a>
				</li>
			</ul>
		</div>
	</div>
</nav>

	<div class="container">
		<?php $this->render (); ?>

		</div>
	<?php echo self::headScript(); ?>
	<?php $this->partial ('script-persona'); ?>
	<p id="version">0.9.0-alpha</p>
	</body>
</html>
