<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8">
		<?php echo self::headTitle(); ?>
		<?php echo self::headStyle(); ?>
		<?php echo self::headScript(); ?>
	</head>
	<body>
	
<header>
	<h1 id="title"><a href="<?php echo Url::display (); ?>"><?php echo Configuration::title (); ?></a></h1>
	<h2 id="subtitle">Organisons-nous, tranquillement.</h2>
</header>

<div id="global">
<?php $this->render (); ?>
</div>

<footer>
	<?php if (!is_logged ()) { ?>
	<a id="signin" href="#" class="persona-button"><span>Sign in</span></a>
	<?php } else { ?>
	<a id="signout" href="#" class="persona-button"><span>Sign out - <?php echo Session::param ('mail'); ?></span></a>
	<?php } ?>
	<br />Code disponible sur <a href="https://github.com/marienfressinaud/Apprentidate">GitHub</a>
</footer>

<?php $this->partial ('script-persona'); ?>

	</body>
</html>
