<?php
	$mail = Session::param ('mail', 'null');
	if ($mail != 'null') {
		$mail = '\'' . $mail . '\'';
	}
?>
<script type="text/javascript">
login_url = '<?php echo Url::display (array ("a" => "login")); ?>';
logout_url = '<?php echo Url::display (array ("a" => "logout")); ?>';
currentUser = <?php echo $mail; ?>;

var signinLink = $('a#signin');
if (signinLink) {
	signinLink.click(function() {
		navigator.id.request();
	});
};
 
var signoutLink = $('a#signout');
if (signoutLink) {
	signoutLink.click(function() {
		navigator.id.logout();
	});
};

navigator.id.watch({
  loggedInUser: currentUser,
  onlogin: function(assertion) {
    // A user has logged in! Here you need to:
    // 1. Send the assertion to your backend for verification and to create a session.
    // 2. Update your UI.
    $.ajax({
      type: 'POST',
      url: login_url,
      data: {assertion: assertion},
      success: function(res, status, xhr) { window.location.reload(); },
      error: function(res, status, xhr) { alert("login failure" + res); }
    });
  },
  onlogout: function() {
    // A user has logged out! Here you need to:
    // Tear down the user's session by redirecting the user or making a call to your backend.
    // Also, make sure loggedInUser will get set to null on the next page load.
    // (That's a literal JavaScript null. Not false, 0, or undefined. null.)
    $.ajax({
      type: 'POST',
      url: logout_url,
      success: function(res, status, xhr) { window.location.reload(); },
      error: function(res, status, xhr) { alert("logout failure" + res); }
    });
  }
});
</script>
