<div id="index_about" class="row">
	<h2>À propos de <em>Apprentidate</em></h2>
	<p>
		Apprentidate est une application web développée par Marien Fressinaud permettant de gérer des évenements.<br/>
		Elle permet de créer des sondages sur le modèle de Doodle mais aussi des événements.<br/>
		Le code source est disponible sur GitHub <a href="https://github.com/marienfressinaud/Apprentidate">ici</a> sous license <a href="http://www.gnu.org/licenses/agpl-3.0.html">AGPL v3</a>.
	</p>
</div>
