<div id="index_about">
	<h2>À propos de <em>Apprentidate</em></h2>
	<p>
		Apprentidate est une application web permettant de gérer des évenements et/ou des sondages. Elle se veut une alternative à Doodle, Framadate et autres références.<br/>
		Le code source est disponible sur <a href="https://github.com/apprentimag/Apprentidate">GitHub</a> sous licence <a href="http://www.gnu.org/licenses/agpl-3.0.html">AGPL v3</a>.
	</p>
</div>
