<div id="main">
	<div class="post">
		<h3>Créons nos évènements et déterminons une date qui corresponde à tout le monde</h3>
		Doodle, sapu cépalibre,<br />
		Facebook nous vole nos données,<br />
		Sur Google+ y a personne (en plus de nous voler nos données),<br />
		Framadate, on y comprend rien, en plus c'est pas beau.<br />
		<br />
		Alors voici Apprentidate, enfin sur vos écrans !
	</div>
</div>

<div id="sidebar">
	<div id="create_event">
		<a class="button" href="<?php echo Url::display (array ('c' => 'event', 'a' => 'create')); ?>">Créer un évènement</a>
	</div>
	
	<div class="info">
		<?php if ($this->nbEvents === 0) { ?>
		Aucun évènement n'a encore jamais été créé !
		<?php } else { ?>
		<?php $pluriel = ($this->nbEvents > 1) ? 's' : '';  ?>
		Déjà <?php echo $this->nbEvents; ?> évènement<?php echo $pluriel; ?> créé<?php echo $pluriel; ?> !
		<?php } ?>
	</div>
</div>
