<div id="main">
	<div class="post">Créons nos évènements et déterminons une date qui corresponde à tout le monde !</div>
</div>

<div id="sidebar">
	<div id="create_event">
		<a class="button" href="<?php echo Url::display (array ('c' => 'event', 'a' => 'create')); ?>">Créer un évènement</a>
	</div>
	
	<div class="info">
		<?php if ($this->nbEvents === 0) { ?>
		Aucun évènement n'a encore jamais été créé !
		<?php } else { ?>
		<?php $pluriel = ($this->nbEvents > 1) ? 's' : '';  ?>
		Déjà <?php echo $this->nbEvents; ?> évènement<?php echo $pluriel; ?> créé<?php echo $pluriel; ?> !
		<?php } ?>
	</div>
</div>
