version: '3'

services:
  php:
    image: php:7-fpm-alpine3.7
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ..:/var/www/html:z
    environment:
      - APP_ENVIRONMENT=development
      - APP_SECRET_KEY=a-secret-key-to-change-in-production
    user: $USER

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ..:/var/www/html:z
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:z
    links:
      - php
