<div id="event_edit">
	<h2>Éditer un évènement</h2>
	<a href="<?php echo Url::display (array ('c' => 'event', 'a' => 'see', 'params' => array ('id' => $this->event->id ()))); ?>">← Retour à l'évènement</a>

	<form class="form-horizontal" method="post" action="<?php echo Url::display (array ('c' => 'event', 'a' => 'edit', 'params' => array ('id' => $this->event->id ()))); ?>">
		
		<?php if (!empty ($this->missing)) { ?>
		<div class="alert alert-error">Vous n'avez pas rempli tous les champs correctement !</div>
		<?php } ?>

		<div class="control-group <?php if (in_array ('title', $this->missing)) { echo 'error'; } ?>">
			<label class="control-label" for="titleEvent">Titre de l'évènement</label>
			<div class="controls">
				<input class="input-xlarge" type="text" name="title" id="titleEvent" value="<?php echo $this->event->title (); ?>"/>
			</div>
		</div>
		<div class="control-group <?php if (in_array ('author', $this->missing)) { echo 'error'; } ?>">
			<label class="control-label" for="authorEvent">Votre nom</label>
			<div class="controls">
				<input class="input-xlarge" type="text" name="author" id="authorEvent" value="<?php echo $this->event->author (true); ?>" />
			</div>
		</div>
		<div class="control-group<?php if (in_array ('date', $this->missing)) { echo ' error'; } ?>">
			<label class="control-label" for="dateEvent">Date</label>
			<div class="controls">
				<input class="input-xlarge" type="date" name="date" id="dateEvent" value="<?php echo date ('Y-m-d', $this->event->date ()); ?>"></input>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="expirationdateEvent">Date d'expiration des inscriptions</label>
			<div class="controls">
				<input class="input-xlarge" type="date" name="expirationdate" id="expirationdateEvent" value="<?php echo date ('Y-m-d', $this->event->expirationdate ()); ?>" />
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="placeEvent">Lieu</label>
			<div class="controls">
				<input class="input-xlarge" type="text" name="place" id="placeEvent" value="<?php echo $this->event->place (); ?>" />
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="descEvent">Description de l'évènement</label>
			<div class="controls">
				<textarea class="input-xlarge" name="description" id="descEvent"><?php echo $this->event->description (true); ?></textarea>
			</div>
		</div>
		<div class="control-group">
			<div class="controls">
				<button type="submit" class="btn btn-primary input-xlarge">Valider</button>
			</div>
		</div>
	</form>
</div>
