<div class="row" id="event_see">
	<div class="span8">
		<div class="row">
			<?php $author = $this->event->author (); ?>
			<div class="row">
				<h2 class="span"><?php echo $this->event->title (); ?></h2>
				<?php if (!isset ($author['mail']) || (is_logged () && $author['mail'] == Session::param ('mail'))) { ?><a class="span" href="<?php echo Url::display (array ('c' => 'event', 'a' => 'edit', 'params' => array ('id' => $this->event->id ()))); ?>">éditer</a><?php } ?>
			</div>
			<?php $place = $this->event->place (); ?>
			<div class="row"><i class="icon-calendar"></i><strong><?php echo timestamptodate ($this->event->date (), false); ?></strong></div>
			<div class="row"><?php if (!empty ($place)) { echo '<i class="icon-home"></i><strong>' . $place . '</strong>'; } ?></div>
			<div class="row"><i class="icon-user"></i><em><?php echo $author['name']; ?></em></div>
		
			<?php $desc = $this->event->description ();
			if (!empty ($desc)) { ?>
			<div class="row"><?php echo $desc; ?></div>
			<?php } ?>
		</div>
	
		<div class="row" id="commentaires">
			<?php
				$nb = count ($this->commentaires);
				$pluriel = ($nb > 1) ? 's' : '';
			?>
			<h3><?php echo $nb; ?> commentaire<?php echo $pluriel; ?></h3>
		
			<form method="post" action="<?php echo Url::display (array ('c' => 'event', 'a' => 'add_comment', 'params' => array ('id' => $this->event->id ()))); ?>">
				<div class="row">
					<label>Votre nom</label>
					<input type="text" name="user" id="user" class="span6"/>
				</div>
				<div class="row">
					<label>Votre commentaire</label>		
					<textarea name="content" id="content" class="span6"></textarea>
				</div>
				<div class="row">
					<button type="submit" class="span2 btn btn-primary">Commenter</button>
				</div>
			</form>
		
			<?php $i = 0; foreach ($this->commentaires as $c) { $i++; ?>
			<div class="row comment">
				<?php $author = $c->author (); ?>
				<div class="row">
					<img class="span4" src="<?php echo $author['avatar']; ?>" alt="avatar" />
					<div class="span4">
						<div class="row"><i class="icon-user"></i><em><?php echo $author['name']; ?></em></div>
						<div class="row"><i class="icon-calendar"></i><?php echo timestamptodate ($c->date ()); ?></div>
					</div>
				</div>
				<div class="content">
					<?php echo $c->content (); ?>
				</div>
			
				<?php if (is_logged ()) { ?>
				<a class="delete" href="<?php echo Url::display (array ('c' => 'event', 'a' => 'delete_comment', 'params' => array ('idEvent' => $this->event->id (), 'id' => $c->id ()))); ?>">&nbsp;</a>
				<?php } ?>
			</div>
			<?php } ?>
		</div>
	</div>
	<div class="span4" id="rightside">
		<h3>Sondages</h3>
		<?php if (count ($this->polls) > 0) { ?>
		<div class="list_polls box_sidebar">
			<ul class="unstyled polllist">
				<?php foreach ($this->polls as $poll) { ?>
				<li>
					<?php $nbVotants = count ($poll->voters ()); ?>
					<span><a href="<?php echo Url::display (array ('c' => 'poll', 'a' => 'see', 'params' => array ('id' => $poll->id ()))); ?>"><?php echo $poll->title (); ?></a></span>
					<span class="center">(<?php echo $nbVotants; ?> votant<?php echo ($nbVotants > 1) ? 's' : ''; ?>)</span>
				</li>
				<?php } ?>
			</ul>
		</div>
		<?php } ?>
		<div class="row" id="create_event">
			<a class="span2 btn btn-primary" href="<?php echo Url::display (array ('c' => 'poll', 'a' => 'create', 'params' => array ('id' => $this->event->id ()))); ?>">Ajouter un sondage </a>
		</div>
	
		<?php
			$parts = $this->event->participants ();
			$pluriel = (count ($parts) > 1) ? 's' : '';
		?>
	
		<div class="participants box_sidebar">
			<h3>Participant<?php echo $pluriel; ?> (<?php echo count($parts); ?>)</h3>
			<ul class="nav unstyled">
			<?php foreach ($parts as $key => $participant) { ?>
				<li>
					<span class="center"><img src="<?php echo $participant['avatar']; ?>" alt="avatar" /></span>
					<span><?php echo $participant['name']; ?></span>
				
					<?php if (is_logged ()) { ?>
					<a class="delete" href="<?php echo Url::display (array ('c' => 'event', 'a' => 'delete_user', 'params' => array ('idEvent' => $this->event->id (), 'id' => $key))); ?>">&nbsp;</a>
					<?php } ?>
				</li>
			<?php } ?>
			</ul>
		
			<form class="form-search" method="post" action="<?php echo Url::display (array ('c' => 'event', 'a' => 'add_user', 'params' => array ('id' => $this->event->id ()))); ?>">
				<div class="input-append">
					<input type="text" class="search-query" name="user" id="user_sidebar" placeholder="Votre nom" />
					<button class="btn btn-primary" type="submit"><i class="icon-white icon-plus"></i></button>
				</div>
			</form>
		</div>
	</div>
</div>

