<div id="main">
	<div class="post">
		<?php $author = $this->event->author (); ?>
		<h2><?php echo $this->event->title (); ?><?php if (!isset ($author['mail']) || (is_logged () && $author['mail'] == Session::param ('mail'))) { ?><a class="edit" href="<?php echo Url::display (array ('c' => 'event', 'a' => 'edit', 'params' => array ('id' => $this->event->id ()))); ?>">éditer</a><?php } ?></h2>
		<?php $place = $this->event->place (); ?>
		<div class="date_loc">Le <strong><?php echo timestamptodate ($this->event->date (), false); ?></strong><?php if (!empty ($place)) { echo ' à <strong>' . $place . '</strong>'; } ?></div>
		<div class="author">Créé par <em><?php echo $author['name']; ?></em></div>
		
		<?php $desc = $this->event->description ();
		if (!empty ($desc)) { ?>
		<div class="description"><?php echo $desc; ?></div>
		<?php } ?>
	</div>
	
	<div class="post" id="commentaires">
		<?php
			$nb = count ($this->commentaires);
			$pluriel = ($nb > 1) ? 's' : '';
		?>
		<h2><?php echo $nb; ?> commentaire<?php echo $pluriel; ?></h2>
		
		<form method="post" action="<?php echo Url::display (array ('c' => 'event', 'a' => 'add_comment', 'params' => array ('id' => $this->event->id ()))); ?>">
			<input type="text" name="user" id="user" placeholder="Votre nom <adresse@mail>" />
			<textarea name="content" id="content" placeholder="Votre commentaire"></textarea>
			<input class="button" type="submit" value="Commenter" />
		</form>
		
		<?php $i = 0; foreach ($this->commentaires as $c) { $i++; ?>
		<div class="comment <?php echo ($i % 2 == 0) ? 'even' : 'odd'; ?>">
			<?php $author = $c->author (); ?>
			<div class="avatar"><img src="<?php echo $author['avatar']; ?>" alt="avatar" /></div>
			<div class="content">
				<?php echo $c->content (); ?>
				<span class="more">le <?php echo timestamptodate ($c->date ()); ?> par <em><?php echo $author['name']; ?></em></span>
			</div>
			
			<?php if (is_logged ()) { ?>
			<a class="delete" href="<?php echo Url::display (array ('c' => 'event', 'a' => 'delete_comment', 'params' => array ('idEvent' => $this->event->id (), 'id' => $c->id ()))); ?>">&nbsp;</a>
			<?php } ?>
		</div>
		<?php } ?>
	</div>
</div>

<div id="sidebar">
	<div id="create_event">
		<a class="button" href="<?php echo Url::display (array ('c' => 'event', 'a' => 'create')); ?>">Créer un évènement</a>
	</div>
	
	<?php
		$parts = $this->event->participants ();
		$pluriel = (count ($parts) > 1) ? 's' : '';
	?>
	
	<div class="participants">
		<div class="nbParticipants"><?php echo count($parts); ?> participant<?php echo $pluriel; ?></div>
		<ul>
		<?php foreach ($parts as $key => $participant) { ?>
			<li>
				<span class="avatar"><img src="<?php echo $participant['avatar']; ?>" alt="avatar" /></span>
				<span><?php echo $participant['name']; ?></span>
				
				<?php if (is_logged ()) { ?>
				<a class="delete" href="<?php echo Url::display (array ('c' => 'event', 'a' => 'delete_user', 'params' => array ('idEvent' => $this->event->id (), 'id' => $key))); ?>">&nbsp;</a>
				<?php } ?>
			</li>
		<?php } ?>
		</ul>
		
		<form class="add_user" method="post" action="<?php echo Url::display (array ('c' => 'event', 'a' => 'add_user', 'params' => array ('id' => $this->event->id ()))); ?>">
			<input type="text" name="user" id="user_sidebar" placeholder="Votre nom <adresse@mail>" />
			<input type="submit" value="+" />
		</form>
	</div>
</div>
