<div class="row" id="event_see">
	<div class="span8">
		<ul class="event">
			<?php $author = $this->event->author (); ?>
			<li>
				<h2><?php echo $this->event->title (); ?></h2>
			</li>

			<li><i class="icon-calendar"></i> Le <strong><?php echo timestamptodate ($this->event->date (), true); ?></strong></li>

			<?php $place = $this->event->place (); ?>
			<?php if (!empty ($place)) { ?>
			<li>
				<i class="icon-home"></i> à <strong><?php echo $place; ?></strong>
			</li>
			<?php } ?>

			<li><i class="icon-user"></i> par <strong><?php echo $author['name']; ?></strong></li>

			<li>
				<?php if ($this->isAdmin) { ?>
				<a href="<?php echo Url::display (array ('c' => 'event', 'a' => 'edit', 'params' => array ('id' => $this->event->id ()))); ?>"><i class="icon-edit"></i> Éditer</a>
				<?php } else { ?>
				<a href="<?php echo Url::display (array ('c' => 'event', 'a' => 'auth', 'params' => array ('id' => $this->event->id ()))); ?>"><i class="icon-edit"></i> Administration</a>
				<?php } ?>
			</li>
		
			<?php $desc = $this->event->description ();
			if (!empty ($desc)) { ?>
			<li><p class="well"><?php echo $desc; ?></p></li>
			<?php } ?>
		</ul>

		<hr />
	
		<div class="commentaires">
			<?php
				$nb = count ($this->commentaires);
				$pluriel = ($nb > 1) ? 's' : '';
			?>
			<h3><?php echo $nb; ?> commentaire<?php echo $pluriel; ?></h3>

			<form method="post" action="<?php echo Url::display (array ('c' => 'event', 'a' => 'add_comment', 'params' => array ('id' => $this->event->id ()))); ?>" class="form-horizontal">
				<div class="control-group">
					<label class="control-label" for="user">Votre nom</label>
					<div class="controls">
						<input type="text" name="user" id="user" class="input-xlarge" />
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="content">Votre commentaire</label>
					<div class="controls">	
						<textarea name="content" id="content" class="input-xlarge" ></textarea>
					</div>
				</div>
				<div class="control-group">
					<div class="controls">
						<button type="submit" class="btn input-xlarge">Commenter</button>
					</div>
				</div>
			</form>

			<ul class="media-list">
				<?php $i = 0; foreach ($this->commentaires as $c) { $i++; ?>
				<?php $author = $c->author (); ?>
				<li class="media">
					<img class="media-object pull-left avatar img-polaroid" src="<?php echo $author['avatar']; ?>" alt="avatar" />
					<div class="media-body">
						<ul class="media-heading">
							<li><i class="icon-user"></i> <?php echo $author['name']; ?></li>
							<li><i class="icon-calendar"></i> <?php echo timestamptodate ($c->date ()); ?></li>
							<?php if ($this->isAdmin) { ?>
							<li><a class="btn btn-mini" href="<?php echo Url::display (array ('c' => 'event', 'a' => 'delete_comment', 'params' => array ('idEvent' => $this->event->id (), 'id' => $c->id ()))); ?>"><i class="icon-remove"></i> Supprimer</a></li>
							<?php } ?>
						</ul>

						<p><?php echo $c->content (); ?></p>
					</div>
				</li>
				<?php } ?>
			</ul>
		</div>
	</div>


	<div class="span4" id="rightside">
		<h3>Sondages</h3>
		<?php if (count ($this->polls) > 0) { ?>
		<div class="list_polls box_sidebar">
			<ul class="unstyled polllist">
				<?php foreach ($this->polls as $poll) { ?>
				<li>
					<?php $nbVotants = count ($poll->voters ()); ?>
					<span><a href="<?php echo Url::display (array ('c' => 'poll', 'a' => 'see', 'params' => array ('id' => $poll->id ()))); ?>"><?php echo $poll->title (); ?></a></span>
					<span class="center">(<?php echo $nbVotants; ?> votant<?php echo ($nbVotants > 1) ? 's' : ''; ?>)</span>
				</li>
				<?php } ?>
			</ul>
		</div>
		<?php } ?>

		<?php if ($this->isAdmin) { ?>
		<div class="row" id="create_event">
			<a class="span2 btn btn-primary" href="<?php echo Url::display (array ('c' => 'poll', 'a' => 'create', 'params' => array ('id' => $this->event->id ()))); ?>"><i class="icon-plus-sign icon-white"></i> Créer un sondage</a>
		</div>
		<?php } ?>

		<hr />
	
		<?php
			$parts = $this->guests;
			$pluriel = (count ($parts) > 1) ? 's' : '';
		?>
	
		<div class="participants box_sidebar">
			<h3>Participant<?php echo $pluriel; ?> (<?php echo count($parts); ?>)</h3>
			<ul class="media-list">
			<?php foreach ($parts as $key => $participant) { ?>
				<li class="media">
					<img class="media-object pull-left avatar img-polaroid" src="<?php echo $participant->avatar(); ?>" alt="avatar" />

					<div class="media-body">
						<h4 class="media-heading"><?php echo $participant->name(); ?></h4>
						<a class="btn-mini btn" href="<?php echo Url::display (array ('c' => 'event', 'a' => 'delete_user', 'params' => array ('idEvent' => $this->event->id (), 'id' => $participant->id()))); ?>"><i class="icon-minus-sign"></i>Désinscrire</a>
					</div>
				</li>
			<?php } ?>
			</ul>
			<?php
				if($this->event->expirationdate() > time ()) {
			?>
			<form class="form-inline" method="post" action="<?php echo Url::display (array ('c' => 'event', 'a' => 'add_user', 'params' => array ('id' => $this->event->id ()))); ?>">
				<div class="input-append">
					<input type="text" class="input-block-level" name="user" id="user_sidebar" placeholder="Votre nom" />
					<button class="btn btn-primary" type="submit"><i class="icon-white icon-plus"></i></button>
				</div>
			</form>
			<p>Les inscriptions se fermeront le <?php echo timestamptodate ($this->event->expirationdate(), true); ?>.</p>
			<?php
				} else {
			?>
				<p>Les inscriptions sont fermées.</p>
			<?php
				}
			?>
		</div>
	</div>
</div>

